### ISSUE TITLE
formatted="false" support

### ISSUE THREAD

**Issue by ingbrzy** [redmaner/MA-XML-CHECK#23]
If in the string are used two same variables, has to be added formatted="false" to the string name otherwise recompile failed...

https://github.com/ingbrzy/MA-XML-7.0-SPANISH/commit/7848d442091e149f18395170934b0e699faaedcb

**Comment by redmaner** [comment]
A new challenge, I'll see if I can win.

**Comment by redmaner** [comment]
Is formatted="false" only required for the exact same variables like 2 x %s or also for strings that has for example $1%d $2%d $3%d?

**Comment by ingbrzy** [comment]
Only for exactly same variables..

**Comment by redmaner** [comment]
I won the challenge. This check is currently limited to strings.xml only. 
Let me know if this check should also be done on plurals and arrays.

I will recheck all languages on translators.xiaomi.eu so that every language is checked for formatted="false"
